name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image to Docker Hub
      run: |
        docker build -t node-hello .
        docker push node-hello:latest

    - name: Deploy to ECS
      run: |
        # Assuming you have an ECS task definition and service already created
        # Update the ECS service with the new task definition revision
        aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment
